# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9c51356d5d158c545a59b17315075b94bf02af3a136c44762637bb370098b7a7ba2525f6ee26546d06c5dec61d2b66313bdf1879a76f4211947076ee362fdca

test:
  secret_key_base: a6fc8ec62844ed65cc12cb53eefbd13dfc8f6ff633186fadf5f2d56100bd21d393e5007c88be96140c4263756a3cdeca8fdac95f28cfbecf708ccb311736489a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
